FROM node:22-alpine@sha256:16e22a550f3863206a3f701448c45f7912c6896a62de43add43bb9c86130c3e2
WORKDIR /app
RUN npm init -y && npm install redis@4
COPY redis-rest-proxy.mjs .
EXPOSE 80
CMD ["node", "redis-rest-proxy.mjs"]
